/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\joker.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, useTexture } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function JokerModel(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./model/joker.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  const jokerFace = useTexture('./joker/joker_whiteFace.png')

nodes.Joker008_2.material.map = jokerFace
nodes.Joker008_2.material.needsUpdate = true

  return (
    <group ref={group} position={[0,-2, 3]} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Hips} />
          <group name="Body">
            <skinnedMesh name="Joker008" geometry={nodes.Joker008.geometry} material={materials.black} skeleton={nodes.Joker008.skeleton} morphTargetDictionary={nodes.Joker008.morphTargetDictionary} morphTargetInfluences={nodes.Joker008.morphTargetInfluences} />
            <skinnedMesh name="Joker008_1" geometry={nodes.Joker008_1.geometry} material={materials.Eyes} skeleton={nodes.Joker008_1.skeleton} morphTargetDictionary={nodes.Joker008_1.morphTargetDictionary} morphTargetInfluences={nodes.Joker008_1.morphTargetInfluences} />
            <skinnedMesh name="Joker008_2" geometry={nodes.Joker008_2.geometry} material={materials.Face} skeleton={nodes.Joker008_2.skeleton} morphTargetDictionary={nodes.Joker008_2.morphTargetDictionary} morphTargetInfluences={nodes.Joker008_2.morphTargetInfluences} />
            <skinnedMesh name="Joker008_3" geometry={nodes.Joker008_3.geometry} material={materials.Neck} skeleton={nodes.Joker008_3.skeleton} morphTargetDictionary={nodes.Joker008_3.morphTargetDictionary} morphTargetInfluences={nodes.Joker008_3.morphTargetInfluences} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./model/joker.glb')
