/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\x-wing.glb 
Author: Blargenswarg (https://sketchfab.com/Blargenswarg)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/x-wing-62762bb28f464d79969b6914c5dd3af3
Title: X-Wing
*/


import { Float, useGLTF } from "@react-three/drei";
import {  ShaderMaterial } from "three";
import { vertexShader, fragmentShader } from "./shaders/model/shaders";
import { useFrame } from "@react-three/fiber";

export function Model({wireframe}) {
  const { nodes, materials } = useGLTF("./model/x-wing.glb");

    const material = new ShaderMaterial({
      vertexShader: vertexShader,
      fragmentShader: fragmentShader,
      wireframe: true,
      uniforms: {
        time: { value: 0 },
      },
      transparent: true,
      depthWrite: false,
      
    });

    useFrame(({ clock }) => {
      material.uniforms.time.value = clock.getElapsedTime();
    });
  
  return (
    // <Float>
      <group  scale={0.4} position={[0, -3, -1]} dispose={null}>
        <mesh
          geometry={nodes.polySurface149_lambert1_0.geometry}
          material={wireframe ? material : materials.lambert1}
          scale={1}
        />
      </group>
    // </Float>
  );
}

useGLTF.preload("./model/x-wing.glb");
